<?php
/*
	Question2Answer by Gideon Greenspan na contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it na/au
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, au (at your chaguo) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; yasiyo na even the implied warranty of
	MERCHANTABILITY au FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about hiki license: http://www.question2answer.org/license.php
*/

return array(
	'_decimal_point' => '.',
	'_thousands_separator' => ',',
	'_thousands_suffix' => 'k',
	'_millions_suffix' => 'm',
	'1_answer' => 'jibu 1',
	'1_comment' => 'maoni 1',
	'1_day' => 'siku 1',
	'1_disliked' => 'dislike 1',
	'1_flag' => 'flag 1',
	'1_hour' => 'saa 1',
	'1_liked' => 'like 1',
	'1_minute' => 'dakika 1',
	'1_month' => 'mwezi 1',
	'1_point' => 'alama 1',
	'1_question' => 'swali 1',
	'1_second' => 'sekunde 1',
	'1_tag' => 'kitambulisho 1',
	'1_user' => 'mtumiaji 1',
	'1_view' => 'mtazamo 1',
	'1_vote' => 'kura 1',
	'1_week' => 'wiki 1',
	'1_year' => 'mwaka 1',
	'add_category_x_favorites' => 'Ongeza kikundi ^ kwa vipendwa vyangu',
	'add_favorites' => 'Ongeza kwa vipendwa vyangu',
	'add_tag_x_favorites' => 'Ongeza kitambulisho ^ kwa vipendwa vyangu',
	'all_categories' => 'Vikundi vyote',
	'anonymous' => 'Asiyejulikana',
	'answer_edited' => 'jibu limehaririwa',
	'answer_reshown' => 'jibu limeonyeshwa upya',
	'answer_selected' => 'jibu limechaguliwa',
	'answered' => 'alijibu',
	'answered_qs_in_x' => 'Maswali yaliyojibiwa sana katika ^',
	'answered_qs_title' => 'Maswali yaliyojibiwa sana',
	'asked' => 'aliuliza',
	'asked_related_q' => 'aliuliza swali linalohusiana',
	'by_x' => 'na ^',
	'cancel_button' => 'Ghairi',
	'closed' => 'limefungwa',
	'comment_edited' => 'maoni yamehaririwa',
	'comment_moved' => 'maoni yamebadilishwa',
	'comment_reshown' => 'maoni yameonyeshwa upya',
	'alitoa maoni' => 'alitoa maoni',
	'date_day_min_digits' => 1, // 1 au 2
	'date_format_other_years' => '^month ^day, ^year',
	'date_format_this_year' => '^month ^day',
	'date_month_1' => 'Jan',
	'date_month_2' => 'Feb',
	'date_month_3' => 'Mar',
	'date_month_4' => 'Apr',
	'date_month_5' => 'May',
	'date_month_6' => 'Jun',
	'date_month_7' => 'Jul',
	'date_month_8' => 'Aug',
	'date_month_9' => 'Sep',
	'date_month_10' => 'Oct',
	'date_month_11' => 'Nov',
	'date_month_12' => 'Dec',
	'date_year_digits' => 4, // 2 au 4
	'limehaririwa' => 'limehaririwa',
	'email_error' => 'Kosa limetokea katika kujaribu kutuma barua pepe.',
	'field_required' => 'Tafadhali andika kitu kwenye uga huu',
	'file_upload_limit_exceeded' => 'Ukubwa wa faili hii unazidi kipimo cha seva',
	'general_error' => 'Kosa la seva limetokea - tafadhali jaribu tena.',
	'hidden' => 'imefichwa',
	'highest_users' => 'Watumiaji wenye alama za juu',
	'hot_qs_in_x' => 'Maswali moto katika ^',
	'hot_qs_title' => 'Maswali moto',
	'image_not_read' => 'Picha haingeweza kusomwa. Tafadhali pakia moja ya: ^',
	'image_too_big_x_pc' => 'Picha hii ni kubwa sana. Tafadhali ipunguze hadi asilimia ^% halafu ujaribu tena.',
	'in_category_x' => 'katika ^',
	'ip_address_x' => 'Anwani ya IP ^',
	'logged_in_x' => 'Hujambo ^',
	'max_length_x' => 'Ukubwa wa juu wa herufi ^',
	'max_upload_size_x' => 'Ukubwa wa juu wa kupakia ni ^',
	'me' => 'mimi',
	'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <alijibu> <15 hours ago> <in Problems> <by me (500 points)>
	'min_length_x' => 'Tafadhali peana maelezo zaidi - angalau herufi ^',
	'moved' => 'imebadilishwa',
	'nav_activity' => 'Shughuli zote',
	'nav_admin' => 'Usimamizi',
	'nav_ask' => 'Uliza Swali',
	'nav_categories' => 'Vikundi',
	'nav_feedback' => 'Tuma maoni',
	'nav_home' => 'Nyumbani',
	'nav_hot' => 'Moto!',
	'nav_login' => 'Ingia',
	'nav_logout' => 'Ondoka',
	'nav_most_answers' => 'Yenge majibu mengi',
	'nav_most_recent' => 'Ya hivi karibuni',
	'nav_most_views' => 'Yenye mitazamo mingi',
	'nav_most_votes' => 'Yenge Kura nyingi',
	'nav_no_answer' => 'Hamna jibu',
	'nav_no_selected_answer' => 'Hamna jibu limechaguliwa',
	'nav_no_upvoted_answer' => 'Hamna jibu limepigiwa kura',
	'nav_qa' => 'Q&A',
	'nav_qs' => 'Maswali',
	'nav_register' => 'Jisajili',
	'nav_tags' => 'Vitambulisho',
	'nav_unanswered' => 'Hayajajibiwa',
	'nav_updates' => 'Taarifa zangu',
	'nav_users' => 'Watumiaji',
	'newest_users' => 'Watumiaji wapya',
	'no_active_users' => 'Hamna watumiaji waliopo wamepatikana',
	'no_answers_found' => 'Hamna majibu yamepatikana',
	'no_answers_in_x' => 'Hamna majibu katika ^',
	'no_categories_found' => 'Hamna vikundi vimepatikana',
	'no_category' => 'Hamna kikundi',
	'no_comments_found' => 'Hamna maoni yamepatikana',
	'no_comments_in_x' => 'Hamna maoni katika ^',
	'no_questions_found' => 'Hamna maswali yamepatikana',
	'no_questions_in_x' => 'Hamna maswali katika ^',
	'no_related_qs_title' => 'Hamna maswali yanayohusiana yamepatikana',
	'no_results_for_x' => 'Hamna matokeo yamepatikana kwa ajili ya ^',
	'no_tags_found' => 'Hamna vitambulisho vimepatikana',
	'no_una_questions_found' => 'Hamna maswali yasiyojibiwa yamepatikana',
	'no_una_questions_in_x' => 'Hamna maswali yasiyojibiwa katika ^',
	'no_unselected_qs_found' => 'Hamna maswali yamepatikana bila jibu limechaguliwa',
	'no_unupvoteda_qs_found' => 'Hamna maswali yamepatikana bila jibu lililopigiwa kura',
	'page_label' => 'Ukurasa:',
	'page_next' => 'inayofwata',
	'page_not_found' => 'Ukurasa haujapatikana',
	'page_prev' => 'iliyopita',
	'popular_tags' => 'Vitambulisho vilivyovuma',
	'questions_tagged_x' => 'Maswali ya hivi karibuni yaliyotambulishwa ^',
	'recategorized' => 'yamepewa vikundi vipya',
	'recent_activity_in_x' => 'Shughuli ya hivi karibuni katika ^',
	'recent_activity_title' => 'Shughuli ya hivi karibuni',
	'recent_as_in_x' => 'Hivi karibuni alijibu maswali katika ^',
	'recent_as_title' => 'Hivi karibuni alijibu maswali',
	'recent_cs_in_x' => 'Hivi karibuni alitoa maoni maswali katika ^',
	'recent_cs_title' => 'Hivi karibuni alitoa maswali maoni',
	'recent_qs_as_in_x' => 'Maswali na majibu ya hivi karibuni katika ^',
	'recent_qs_as_title' => 'Maswali na majibu ya hivi karibuni',
	'recent_qs_in_x' => 'Maswali ya hivi karibuni katika ^',
	'recent_qs_title' => 'Maswali ya hivi karibuni',
	'related_qs_title' => 'Maswali ya hivi karibuni',
	'remove_favorites' => 'Ondoa kutoka kwa vipendwa vyangu',
	'remove_x_favorites' => 'Ondoa ^ kutoka kwa vipendwa vyangu',
	'reopened' => 'imefunguliwa upya',
	'limeonyeshwa upya' => 'limeonyeshwa upya',
	'results_for_x' => 'Matokeo ya utafutaji kwa ^',
	'retagged' => 'imetambulishwa upya',
	'save_button' => 'Hifadhi Mabadiliko',
	'search_button' => 'Tafuta',
	'search_explanation' => 'Tafadhali andika maneno fulani kwenye sehemu ya kutafuta na ujaribu tena.',
	'search_title' => 'Matokeo ya utafutaji',
	'limechaguliwa' => 'limechaguliwa',
	'send_button' => 'Tuma',
	'since_x' => 'tangu ^',
	'suggest_ask' => 'Saidia kuanzisha mambo kwa ^1kuuliza swali^2.',
	'suggest_category_qs' => 'Ili kuona zaidi, bonyeza kwa ajili ya ^1maswali yote katika kikundi hiki^2.',
	'suggest_qs' => 'Ili kuona zaidi, bonyeza kwa ajili ya ^1orodha yote ya maswali^2.',
	'suggest_qs_tags' => 'Ili kuona zaidi, bonyeza kwa ajili ya  ^1orodha yote ya maswali^2 au ^3vitambulisho vilivyovuma^4.',
	'to_x' => 'kwa ^',
	'unanswered_qs_in_x' => 'Maswali yasiyo na majibu katika ^',
	'unanswered_qs_title' => 'Maswali ya hivi karibuni yasiyo na majibu',
	'unselected_qs_in_x' => 'Maswali yasiyo na jibu limechaguliwa katika ^',
	'unselected_qs_title' => 'Maswali ya hivi karibuni yasiyo na a limechaguliwa jibu',
	'unupvoteda_qs_in_x' => 'Maswali yasiyo na jibu lililopigiwa kura katika ^',
	'unupvoteda_qs_title' => 'Recent maswali ya hivi karibuni yasiyo na jibu lililopigiwa kura',
	'upload_limit' => 'Umepakia sana - tafadhali jaribu tena saa moja baadaye',
	'view_q_must_be_approved' => 'Sharti akaunti yako iidhinishwe ili uweze kuona kurasa za maswali. Tafadhali subiri au ^1ongeza maelezo zaidi^2.',
	'view_q_must_confirm' => 'Tafadhali ^5thibithisha anwani yako ya barua pepe^6 ili uweze kuona kurasa za maswali.',
	'view_q_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili uweze kuona kurasa za maswali.',
	'viewed_qs_in_x' => 'Maswali yaliyoonwa sana katika ^',
	'viewed_qs_title' => 'Maswali yaliyoonwa sana',
	'vote_disabled_approve' => 'Sharti akaunti yako iidhinishwe kabla uweze kupiga kura',
	'vote_disabled_down' => 'Kupiga kura za chini kunapatikana kwa watumiaji fulani tu',
	'vote_disabled_down_approve' => 'Sharti akaunti yako iidhinishwe kabla uweze kupiga kura ya chini',
	'vote_disabled_hidden_post' => 'Huwezi kupiga kura ya chini chapisho lililofichwa',
	'vote_disabled_hidden_a' => 'Huwezi kupiga kura jibu liliofichwa',  // @deprecated
	'vote_disabled_hidden_q' => 'Huwezi kupiga kura swali liliofichwa',  // @deprecated
	'vote_disabled_level' => 'Kupiga kura kunapatikana kwa watumiaji fulani tu',
	'vote_disabled_my_post' => 'Huwezi kupiga kura ya chini chapisho lako',
	'vote_disabled_my_a' => 'Huwezi kupiga kura ya chini jibu lako',  // @deprecated
	'vote_disabled_my_q' => 'Huwezi kupiga kura ya chini maswali yako',  // @deprecated
	'vote_disabled_q_page_only' => 'Tafadhali fungua swali hili ili kupiga kura',
	'vote_disabled_queued' => 'Unaweza kupiga kura kwa chapisho lililoidhinishwa pekee',
	'vote_down_must_confirm' => 'Tafadhali ^5thibithisha anwani yako ya barua pepe^6 to vote down.',
	'vote_down_popup' => 'Bonyeza ili kupiga kura ya chini',
	'vote_limit' => 'Kura nyingi zimepatikana - tafadhali jaribu tena saa moja baadaye',
	'vote_must_confirm' => 'Tafadhali ^5thibithisha anwani yako ya barua pepe^6 ili uweze kupiga kura.',
	'vote_must_login' => 'Tafadhali ^1ingia^2 au ^3jisajili^4 ili uweze kupiga kura.',
	'vote_not_allowed' => 'Haurusiwi kupiga kura hapa',
	'vote_up_popup' => 'Bonyeza ili kupiga kura ya juu',
	'voted_down_popup' => 'Umepigia hili kura ya chini - bonyeza kuondoa kura',
	'voted_qs_in_x' => 'Maswali yenye kura nyingi katika ^',
	'voted_qs_title' => 'Maswali yenye kura nyingi',
	'voted_up_popup' => 'Umepigia hili kura ya juu - bonyeza kuondoa kura',
	'written' => '', // blank in English - placeholder for other languages
	'x_ago' => '^ ago',
	'x_answers' => 'majibu ^',
	'x_comments' => 'maoni ^',
	'x_days' => 'siku ^',
	'x_disliked' => 'dislikes ^',
	'x_flags' => 'flags ^',
	'x_hours' => 'masaa ^',
	'x_liked' => 'likes ^',
	'x_minutes' => 'minutes ^',
	'x_months' => 'miezi ^',
	'x_points' => 'alama ^',
	'x_questions' => 'maswali ^',
	'x_seconds' => 'sekunde ^',
	'x_tags' => 'vitambulisho ^',
	'x_users' => 'watumiaji ^',
	'x_views' => 'mitazamo ^ ',
	'x_votes' => 'kura ^',
	'x_weeks' => 'wiki ^',
	'x_years' => 'miaka ^',
);
