<?php
/*
	Question2Answer by Gideon Greenspan na contributors
	http://www.question2answer.org/

	Description: Language phrases for swali page


	This program is free software; you can redistribute it na/au
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, au (at your chaguo) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY au FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about hiki license: http://www.question2answer.org/license.php
*/

return array(
	'1_answer_title' => '1 Jibu',
	'a_convert_to_c' => 'Convert hiki jibu into a maoni',
	'a_convert_to_c_on' => 'Convert hiki jibu into a maoni on:',
	'a_convert_warn' => 'Warning: This conversion cannot be reversed.',
	'a_convert_warn_cs' => 'Warning: This conversion cannot be reversed na will also move hiki jibu\'s maoni.',
	'a_notify_email' => 'Email me at hiki address if my jibu is selected au alitoa maoni on:',
	'a_notify_label' => 'Email me if my jibu is selected au alitoa maoni on',
	'a_notify_x_label' => 'Email me (^) if my jibu is selected au alitoa maoni on',
	'a_waiting_your_approval' => 'This jibu is waiting for your approval',
	'a_your_waiting_approval' => 'Your jibu will be checked na approved shortly.',
	'add_answer_button' => 'Ongeza jibu',
	'add_comment_button' => 'Ongeza maoni',
	'add_q_favorites' => 'Ongeza hiki swali to my favorites',
	'anon_name_label' => 'Your name to display (optional):',
	'answer_button' => 'jibu',
	'answer_limit' => 'Too many majibu received - please try again in an hour',
	'answer_must_be_approved' => 'Your account must be approved before you jibu a swali. Please wait au ^1add more information^2.',
	'answer_must_confirm' => 'Please ^5confirm your email address^6 to jibu hiki swali.',
	'answer_must_login' => 'Please ^1log in^2 au ^3register^4 to jibu hiki swali.',
	'answer_q_popup' => 'Jibu hiki swali',
	'approve_a_popup' => 'Idhinisha hiki jibu',
	'approve_button' => 'approve',
	'approve_c_popup' => 'Idhinisha hiki maoni',
	'approve_q_popup' => 'Idhinisha hiki swali',
	'ask_button' => 'Uliza the Swali',
	'ask_follow_from_a' => 'Your swali will be related to hiki jibu:',
	'ask_follow_title' => 'Uliza a related swali',
	'ask_limit' => 'Too many maswali received - please try again in an hour',
	'ask_must_be_approved' => 'Your account must be approved before you uliza a swali. Please wait au ^1add more information^2.',
	'ask_must_confirm' => 'Please ^5confirm your email address^6 to uliza a swali.',
	'ask_must_login' => 'Please ^1log in^2 au ^3register^4 to uliza a swali.',
	'ask_same_q' => 'Before proceeding, please check your swali was not aliuliza already:',
	'ask_title' => 'Uliza a swali',
	'c_notify_email' => 'Email me at hiki address if a maoni is added after mine:',
	'c_notify_label' => 'Email me if a maoni is added after mine',
	'c_notify_x_label' => 'Email me (^) if a maoni is added after mine',
	'c_waiting_your_approval' => 'This maoni is waiting for your approval',
	'c_your_waiting_approval' => 'Your maoni will be checked na approved shortly.',
	'category_ask_not_allowed' => 'You do not have permission to uliza maswali in hiki kikundi',
	'category_js_note' => 'To select any kikundi, please enable Javascript in your web browser.',
	'category_required' => 'Please choose a kikundi',
	'claim_a_popup' => 'Assign hiki jibu to your mtumiaji account',
	'claim_button' => 'I wrote hiki',
	'claim_c_popup' => 'Assign hiki maoni to your mtumiaji account',
	'claim_q_popup' => 'Assign hiki swali to your mtumiaji account',
	'clear_flags_button' => 'clear flags',
	'clear_flags_popup' => 'Remove flags by all watumiaji',
	'close_button' => 'close',
	'close_duplicate' => 'This is a duplicate of another swali',
	'close_duplicate_error' => 'The duplicate swali could not be found - please try entering the number from a different swali URL, e.g. 123.',
	'close_form_button' => 'Close swali',
	'close_form_title' => 'Close hiki swali',
	'close_original_note' => 'You can also enter the swali number from the URL, e.g. 123.',
	'close_original_title' => 'URL of the original swali:',
	'close_q_popup' => 'Close hiki swali to any new majibu',
	'close_reason_title' => 'Reason for closing hiki swali, au URL of duplicate swali:',
	'closed_as_duplicate' => 'closed as a duplicate of:',
	'closed_with_note' => 'closed with the note:',
	'comment_a_popup' => 'Ongeza a maoni on hiki jibu',
	'comment_button' => 'maoni',
	'comment_limit' => 'Too many maoni received - please try again in an hour',
	'comment_must_be_approved' => 'Your account must be approved before you ongeza a maoni. Please wait au ^1add more information^2.',
	'comment_must_confirm' => 'Please ^5confirm your email address^6 to ongeza a maoni.',
	'comment_must_login' => 'Please ^1log in^2 au ^3register^4 to ongeza a maoni.',
	'comment_on_a' => 'On jibu: ',
	'comment_on_q' => 'On swali: ',
	'comment_q_popup' => 'Ongeza a maoni on hiki swali',
	'delete_a_popup' => 'Futa hiki jibu permanently',
	'delete_button' => 'futa',
	'delete_c_popup' => 'Futa hiki maoni permanently',
	'delete_q_popup' => 'Futa hiki swali permanently',
	'duplicate_content' => 'Your submission appears to be a duplicate.',
	'edit_a_popup' => 'Hariri hiki jibu',
	'edit_a_title' => 'Hariri jibu',
	'edit_button' => 'hariri',
	'edit_c_popup' => 'Hariri hiki maoni',
	'edit_c_title' => 'Hariri maoni',
	'edit_must_confirm' => 'Please ^5confirm your email address^6 to hariri hiki.',
	'edit_must_login' => 'Please ^1log in^2 au ^3register^4 to hariri hiki.',
	'edit_q_popup' => 'Hariri hiki swali',
	'edit_q_title' => 'Hariri Swali',
	'example_tags' => 'Example tags: ',
	'flag_a_popup' => 'Flag hiki jibu as spam au inappropriate',
	'flag_button' => 'flag',
	'flag_c_popup' => 'Flag hiki maoni as spam au inappropriate',
	'flag_hide_button' => 'flag na hide',
	'flag_limit' => 'Too many chapisho flagged - please try again in an hour',
	'flag_must_confirm' => 'Please ^5confirm your email address^6 to flag chapisho.',
	'flag_must_login' => 'Please ^1log in^2 au ^3register^4 to flag chapisho.',
	'flag_not_allowed' => 'Flagging hiki is not allowed',
	'flag_q_popup' => 'Flag hiki swali as spam au inappropriate',
	'follow_a_popup' => 'Uliza a new swali relating to hiki jibu',
	'follow_button' => 'uliza related swali',
	'follows_a' => 'related to an jibu for:',
	'follows_q' => 'about the swali:',
	'hide_a_popup' => 'Hide hiki jibu',
	'hide_button' => 'hide',
	'hide_c_popup' => 'Hide hiki maoni',
	'hide_q_popup' => 'Hide hiki swali',
	'matching_tags' => 'Matching tags: ',
	'max_tags_x' => 'A maximum of ^ tags are allowed',
	'min_tags_x' => 'Please provide at least ^ tag/s',
	'notify_email_note' => 'Privacy: Your email address will only be used for sending these notifications.',
	'q_category_label' => 'Kikundi:',
	'q_content_label' => 'More information for the swali:',
	'q_hidden_author' => 'This swali has been hidden by its author',
	'q_hidden_flagged' => 'This swali has been flagged na hidden',
	'q_hidden_other' => 'This swali has been hidden',
	'q_notify_email' => 'Email me at hiki address if my swali is alijibu au alitoa maoni on:',
	'q_notify_label' => 'Email me if my swali is alijibu au alitoa maoni on',
	'q_notify_x_label' => 'Email me (^) if my swali is alijibu au alitoa maoni on',
	'q_tags_comma_label' => 'Tags - use comma (,) as a separator:',
	'q_tags_label' => 'Tags - use hyphens to combine words:',
	'q_title_label' => 'The swali in one sentence:',
	'q_waiting_approval' => 'This swali is waiting for approval',
	'q_waiting_your_approval' => 'This swali is waiting for your approval',
	'q_your_waiting_approval' => 'Your swali will be checked na approved shortly.',
	'recat_button' => 'recategorize',
	'recat_popup' => 'Change hiki swali\'s kikundi',
	'recat_q_title' => 'Recategorize swali',
	'reject_a_popup' => 'Reject hiki jibu',
	'reject_button' => 'reject',
	'reject_c_popup' => 'Reject hiki maoni',
	'reject_q_popup' => 'Reject hiki swali',
	'remove_q_favorites' => 'Remove hiki swali from my favorites',
	'reopen_button' => 'reopen',
	'reopen_q_popup' => 'Reopen hiki swali',
	'reply_button' => 'reply',
	'reply_c_popup' => 'Reply to hiki maoni',
	'reshow_a_popup' => 'Reshow hiki jibu',
	'reshow_button' => 'reshow',
	'reshow_c_popup' => 'Reshow hiki maoni',
	'reshow_q_popup' => 'Reshow hiki swali',
	'retag_button' => 'retag',
	'retag_cat_popup' => 'Change hiki swali\'s kikundi au tags',
	'retag_popup' => 'Change hiki swali\'s tags',
	'retag_q_title' => 'Retag swali',
	'save_silent_label' => 'Save silently to hide that hiki was edited',
	'select_popup' => 'Click to select as best jibu',
	'select_text' => 'Best jibu',
	'show_1_comment' => 'Show 1 maoni',
	'show_1_previous_comment' => 'Show 1 previous maoni',
	'show_x_comments' => 'Show ^ maoni',
	'show_x_previous_comments' => 'Show ^ previous maoni',
	'unflag_button' => 'unflag',
	'unflag_popup' => 'Remove the flag that you added',
	'unselect_popup' => 'Click to remove selection',
	'x_answers_title' => '^ Majibu',
	'your_answer_title' => 'Your jibu',
	'your_comment_a' => 'Your maoni on hiki jibu:',
	'your_comment_q' => 'Your maoni on hiki swali:',
);
