<?php
/*
	Question2Answer by Gideon Greenspan na contributors
	http://www.question2answer.org/

	Description: Language phrases for mtumiaji management


	This program is free software; you can redistribute it na/au
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, au (at your chaguo) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY au FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about hiki license: http://www.question2answer.org/license.php
*/

return array(
	'about' => 'About',
	'add_user_x_favorites' => 'Ongeza mtumiaji ^ to my favorites',
	'approve_required' => 'Please wait for your account to be approved au ^1add more information^2.', // @deprecated
	'approve_title' => 'User approval pending',
	'approve_user_button' => 'Idhinisha User',
	'approved_user' => 'Approved mtumiaji',
	'avatar_default' => 'Default',
	'avatar_gravatar' => 'Show my ^1Gravatar^2',
	'avatar_label' => 'Avatar:',
	'avatar_none' => 'None',
	'block_user_button' => 'Block User',
	'blocked_users' => 'Blocked watumiaji',
	'category_level_add' => ' - ^1add kikundi-specific privileges^2',
	'category_level_in' => 'for the kikundi below:',
	'category_level_label' => 'Upgraded to:',
	'category_level_none' => 'No upgrade',
	'change_email_link' => ' - ^1change email^2',
	'change_password' => 'Change Password',
	'confirm_button' => 'Confirm email address',
	'confirm_complete' => 'Thank you - your email address has been confirmed.',
	'confirm_emailed' => 'A confirmation kiungo has been emailed to you. Please click the kiungo to confirm your email address au input the confirmation code below.',
	'confirm_required' => 'To complete your registration, please click the confirmation kiungo that has been emailed to you, au ^1request another^2.',
	'confirm_title' => 'Email Address Confirmation',
	'confirm_wrong_log_in' => 'Code not correct - please ^1log in^2 to send a new kiungo',
	'confirm_wrong_resend' => 'Code not correct - please click below to send a new kiungo',
	'delete_user_button' => 'Futa User',
	'edit_profile' => 'Hariri my Profile',
	'edit_user_button' => 'Hariri User',
	'email_code_another' => 'send another',
	'email_code_emailed' => 'You have been emailed your code',
	'email_code_label' => 'Code:',
	'email_code_wrong' => 'Code not correct',
	'email_confirmed' => 'Confirmed',
	'email_exists' => 'Email already belongs to an account',
	'email_handle_label' => 'Email au Username:',
	'email_invalid' => 'Email is invalid - please check carefully',
	'email_label' => 'Email:',
	'email_not_confirmed' => 'Not yet confirmed',
	'email_please_confirm' => 'Please ^5confirm^6',
	'email_required' => 'Email address required - not public',
	'forgot_link' => 'I forgot my password',
	'full_name' => 'Full name',
	'handle_blocked' => 'Username is disallowed - please try another',
	'handle_empty' => 'Username must not be empty',
	'handle_exists' => 'Username is taken - please try another',
	'handle_has_bad' => 'Username may not contain: ^',
	'handle_label' => 'Username:',
	'hide_all_user_button' => 'Hide all chapisho by hiki mtumiaji',
	'last_login_label' => 'Last login:',
	'last_write_label' => 'Last write action:',
	'level_admin' => 'Administrator',
	'level_editor' => 'Medit',
	'level_expert' => 'Expert',
	'level_for_category' => '^1 for ^2',
	'level_in_general' => 'in general',
	'level_moderator' => 'Moderator',
	'level_super' => 'Super Administrator',
	'location' => 'Location',
	'log_in_to_access' => 'You may now ^1log in^2 to access your account.',
	'login_button' => 'Log In',
	'login_limit' => 'Too many login attempts - please try again in an hour',
	'login_title' => 'Log in',
	'mass_mailings' => 'Mass mailings:',
	'mass_mailings_explanation' => 'Subscribe to emails sent out to all watumiaji',
	'member_for' => 'Member for:',
	'member_type' => 'Type:',
	'new_password_1' => 'New password:',
	'new_password_2' => 'Retype new password:',
	'no_blocked_users' => 'No blocked watumiaji found',
	'no_permission' => 'You do not have permission to perform hiki operation',
	'old_password' => 'Old password:',
	'only_shown_admins' => '(only shown to you na admins)',
	'only_shown_editors' => '(only shown to you, editors na above)',
	'only_shown_experts' => '(only shown to you, experts na above)',
	'only_shown_moderators' => '(only shown to you, moderators na admins)',
	'password_changed' => 'Password changed',
	'password_label' => 'Password:',
	'password_min' => 'Password must be at least ^ characters',
	'password_mismatch' => 'New passwords do not match',
	'password_none' => 'None. To log in directly, set a password below.',
	'password_sent' => 'Your new password was emailed to you',
	'password_to_set' => 'Please set on your account page',
	'password_wrong' => 'Password not correct',
	'private_messages' => 'Private messages:',
	'private_messages_explanation' => 'Allow watumiaji to email you (without seeing your address)',
	'profile_saved' => 'Profile saved',
	'register_button' => 'Register',
	'register_limit' => 'Too many registrations - please try again in an hour',
	'register_suspended' => 'Registration of new watumiaji has been temporarily suspended. Please try again soon.',
	'register_title' => 'Register as a new mtumiaji',
	'registered_label' => 'Registered:',
	'registered_user' => 'Registered mtumiaji',
	'remember' => 'Remember',
	'remember_label' => 'Remember me on hiki computer',
	'remove_avatar' => 'Remove avatar:',
	'reset_title' => 'Reset Forgotten Password',
	'save_profile' => 'Save Profile',
	'save_user' => 'Save User',
	'send_confirm_button' => 'Send Confirmation Link',
	'send_reset_button' => 'Send Reset Password Email',
	'send_reset_note' => 'A message will be sent to your email address with instructions.',
	'special_users' => 'Special watumiaji',
	'terms_not_accepted' => 'You must tick hiki.',
	'unblock_user_button' => 'Unblock User',
	'unsubscribe' => 'Unsubscribe:',
	'unsubscribe_complete' => 'You have been unsubscribed from mass mailings sent out by ^0. You may resubscribe at any time via your ^1account^2 page.',
	'unsubscribe_title' => 'Unsubscribe',
	'unsubscribe_wrong_log_in' => 'Code not correct - please ^1log in^2 to unsubscribe',
	'user_blocked' => '(blocked)',
	'user_not_found' => 'User not found',
	'wall_posts' => 'Wall chapisho:',
	'wall_posts_explanation' => 'Allow watumiaji to chapisho on your wall (you will also be emailed)',
	'website' => 'Website',
	'x_ago_from_y' => '^1 ago from ^2',
);
