<?php
/*
	Question2Answer by Gideon Greenspan na contributors
	http://www.question2answer.org/

	Description: Miscellaneous language phrases


	This program is free software; you can redistribute it na/au
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, au (at your chaguo) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY au FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about hiki license: http://www.question2answer.org/license.php
*/

return array(
	'block_ip_button' => 'Block IP address',
	'browse_categories' => 'Browse vikundi',
	'captcha_approve_fix' => 'This verification will stop appearing once your account is approved.',
	'captcha_confirm_fix' => 'To avoid hiki verification in future, please ^5confirm your email address^6.',
	'captcha_error' => 'Please complete the anti-spam verification',
	'captcha_label' => 'Anti-spam verification:',
	'captcha_login_fix' => 'To avoid hiki verification in future, please ^1log in^2 au ^3register^4.',
	'feed_a_edited_prefix' => 'Jibu edited: ',
	'feed_a_prefix' => 'Alijibu: ',
	'feed_a_reshown_prefix' => 'Jibu reshown: ',
	'feed_a_selected_prefix' => 'Jibu selected: ',
	'feed_c_edited_prefix' => 'Maoni edited: ',
	'feed_c_moved_prefix' => 'Maoni moved: ',
	'feed_c_prefix' => 'Commented: ',
	'feed_c_reshown_prefix' => 'Maoni reshown: ',
	'feed_closed_prefix' => 'Closed: ',
	'feed_edited_prefix' => 'Hariried: ',
	'feed_hidden_prefix' => 'Hidden: ',
	'feed_not_found' => 'Feed not found',
	'feed_recategorized_prefix' => 'Recategorized: ',
	'feed_reopened_prefix' => 'Reopened: ',
	'feed_reshown_prefix' => 'Reshown: ',
	'feed_retagged_prefix' => 'Retagged: ',
	'feedback_email' => 'Your email: (optional)',
	'feedback_empty' => 'Please use hiki uga to send some maoni au suggestions',
	'feedback_message' => 'Your maoni au suggestions for ^:',
	'feedback_name' => 'Your name: (optional)',
	'feedback_sent' => 'Your message below was sent - thank you.',
	'feedback_title' => 'Send feedback',
	'form_security_again' => 'Please click again to confirm',
	'form_security_reload' => 'Please reload the page then try again',
	'hide_all_ip_button' => 'Hide all chapisho from hiki IP',
	'host_name' => 'Host name:',
	'inbox' => 'Inbox',
	'matches_blocked_ips' => 'Matches blocked IP addresses:',
	'message_empty' => 'Please enter your message to send to hiki mtumiaji',
	'message_explanation' => 'This will be sent as a notification from ^. Your email address will not be revealed unless you include it in the message.',
	'message_for_x' => 'Your message for ^:',
	'message_limit' => 'You cannot send more private messages hiki hour',
	'message_must_login' => 'Please ^1log in^2 au ^3register^4 to send private messages.',
	'message_recent_history' => 'Recent correspondence with ^',
	'message_sent' => 'Your private message below was sent',
	'more_favorite_qs' => 'More favorite maswali...',
	'more_favorite_tags' => 'More favorite tags...',
	'more_favorite_users' => 'More favorite watumiaji...',
	'my_favorites_title' => 'My favorites',
	'nav_all_my_updates' => 'All my updates',
	'nav_my_content' => 'My taarifa',
	'nav_my_details' => 'My account',
	'nav_my_favorites' => 'My favorites',
	'nav_user_activity' => 'Recent activity',
	'nav_user_as' => 'All majibu',
	'nav_user_pms' => 'Private messages',
	'nav_user_qs' => 'All maswali',
	'nav_user_wall' => 'Wall',
	'next_step' => 'Next step',
	'no_activity_from_x' => 'No activity from ^',
	'no_favorite_categories' => 'No favorite vikundi',
	'no_favorite_qs' => 'No favorite maswali',
	'no_favorite_tags' => 'No favorite tags',
	'no_favorite_users' => 'No favorite watumiaji',
	'no_recent_updates' => 'No recent updates',
	'no_updates_content' => 'No recent updates for my taarifa',
	'no_updates_favorites' => 'No updates for my favorites',
	'outbox' => 'Sent items',
	'pm_inbox_title' => 'Private messages received',
	'pm_outbox_title' => 'Private messages sent',
	'private_message_title' => 'Send a private message',
	'recent_activity_from_x' => 'Recent activity from ^',
	'recent_updates_content' => 'Recent updates for my taarifa',
	'recent_updates_favorites' => 'Recent updates for my favorites',
	'recent_updates_title' => 'Recent updates for me',
	'site_in_maintenance' => 'This site is currently down for maintenance - please come back soon.',
	'suggest_favorites_add' => 'To ongeza a swali au other item to your favorites, click the ^ at the top of its page.',
	'suggest_update_favorites' => 'For more updates, ongeza items to ^1your favorites^2.',
	'unblock_ip_button' => 'Unblock IP address',
	'your_a_commented' => 'your jibu alitoa maoni',
	'your_a_edited' => 'your jibu edited',
	'your_a_hidden' => 'your jibu hidden',
	'your_a_questioned' => 'aliuliza on your jibu',
	'your_a_reshown' => 'your jibu reshown',
	'your_a_selected' => 'your jibu selected',
	'your_c_edited' => 'your maoni edited',
	'your_c_followed' => 'your maoni followed',
	'your_c_hidden' => 'your maoni hidden',
	'your_c_moved' => 'your maoni moved',
	'your_c_reshown' => 'your maoni reshown',
	'your_q_answered' => 'your swali alijibu',
	'your_q_closed' => 'your swali closed',
	'your_q_commented' => 'your swali alitoa maoni',
	'your_q_edited' => 'your swali edited',
	'your_q_hidden' => 'your swali hidden',
	'your_q_recategorized' => 'your swali recategorized',
	'your_q_reopened' => 'your swali reopened',
	'your_q_reshown' => 'your swali reshown',
	'your_q_retagged' => 'your swali retagged',
);
