<?php
/*
	Question2Answer by Gideon Greenspan na contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it na/au
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, au (at your chaguo) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY au FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about hiki license: http://www.question2answer.org/license.php
*/

return array(
	'_decimal_point' => '.',
	'_thousands_separator' => ',',
	'_thousands_suffix' => 'k',
	'_millions_suffix' => 'm',
	'1_answer' => '1 jibu',
	'1_comment' => '1 maoni',
	'1_day' => '1 day',
	'1_disliked' => '1 dislike',
	'1_flag' => '1 flag',
	'1_hour' => '1 hour',
	'1_liked' => '1 like',
	'1_minute' => '1 minute',
	'1_month' => '1 month',
	'1_point' => '1 point',
	'1_question' => '1 swali',
	'1_second' => '1 second',
	'1_tag' => '1 tag',
	'1_user' => '1 mtumiaji',
	'1_view' => '1 view',
	'1_vote' => '1 vote',
	'1_week' => '1 week',
	'1_year' => '1 year',
	'add_category_x_favorites' => 'Ongeza kikundi ^ to my favorites',
	'add_favorites' => 'Ongeza to my favorites',
	'add_tag_x_favorites' => 'Ongeza tag ^ to my favorites',
	'all_categories' => 'All vikundi',
	'anonymous' => 'anonymous',
	'answer_edited' => 'jibu edited',
	'answer_reshown' => 'jibu reshown',
	'answer_selected' => 'jibu selected',
	'alijibu' => 'alijibu',
	'answered_qs_in_x' => 'Most alijibu maswali in ^',
	'answered_qs_title' => 'Most alijibu maswali',
	'aliuliza' => 'aliuliza',
	'asked_related_q' => 'aliuliza related swali',
	'by_x' => 'by ^',
	'cancel_button' => 'Cancel',
	'closed' => 'closed',
	'comment_edited' => 'maoni edited',
	'comment_moved' => 'maoni moved',
	'comment_reshown' => 'maoni reshown',
	'alitoa maoni' => 'alitoa maoni',
	'date_day_min_digits' => 1, // 1 au 2
	'date_format_other_years' => '^month ^day, ^year',
	'date_format_this_year' => '^month ^day',
	'date_month_1' => 'Jan',
	'date_month_2' => 'Feb',
	'date_month_3' => 'Mar',
	'date_month_4' => 'Apr',
	'date_month_5' => 'May',
	'date_month_6' => 'Jun',
	'date_month_7' => 'Jul',
	'date_month_8' => 'Aug',
	'date_month_9' => 'Sep',
	'date_month_10' => 'Oct',
	'date_month_11' => 'Nov',
	'date_month_12' => 'Dec',
	'date_year_digits' => 4, // 2 au 4
	'edited' => 'edited',
	'email_error' => 'An error occurred trying to send the email.',
	'field_required' => 'Please enter something in hiki uga',
	'file_upload_limit_exceeded' => 'The size of the file exceeds the server\'s limits',
	'general_error' => 'A server error occurred - please try again.',
	'hidden' => 'hidden',
	'highest_users' => 'Top scoring watumiaji',
	'hot_qs_in_x' => 'Hot maswali in ^',
	'hot_qs_title' => 'Hot maswali',
	'image_not_read' => 'The image could not be read. Please upload one of: ^',
	'image_too_big_x_pc' => 'This image is too big. Please scale to ^% then try again.',
	'in_category_x' => 'in ^',
	'ip_address_x' => 'IP address ^',
	'logged_in_x' => 'Hello ^',
	'max_length_x' => 'Maximum length is ^ characters',
	'max_upload_size_x' => 'Maximum upload size is ^',
	'me' => 'me',
	'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <alijibu> <15 hours ago> <in Problems> <by me (500 points)>
	'min_length_x' => 'Please provide more information - at least ^ characters',
	'moved' => 'moved',
	'nav_activity' => 'All Activity',
	'nav_admin' => 'Admin',
	'nav_ask' => 'Uliza a Swali',
	'nav_categories' => 'Vikundi',
	'nav_feedback' => 'Send feedback',
	'nav_home' => 'Home',
	'nav_hot' => 'Hot!',
	'nav_login' => 'Login',
	'nav_logout' => 'Logout',
	'nav_most_answers' => 'Most majibu',
	'nav_most_recent' => 'Recent',
	'nav_most_views' => 'Most views',
	'nav_most_votes' => 'Most votes',
	'nav_no_answer' => 'No jibu',
	'nav_no_selected_answer' => 'No selected jibu',
	'nav_no_upvoted_answer' => 'No upvoted jibu',
	'nav_qa' => 'Q&A',
	'nav_qs' => 'Maswali',
	'nav_register' => 'Register',
	'nav_tags' => 'Tags',
	'nav_unanswered' => 'Unanswered',
	'nav_updates' => 'My Updates',
	'nav_users' => 'Watumiaji',
	'newest_users' => 'Newest watumiaji',
	'no_active_users' => 'No active watumiaji found',
	'no_answers_found' => 'No majibu found',
	'no_answers_in_x' => 'No majibu in ^',
	'no_categories_found' => 'No vikundi found',
	'no_category' => 'No kikundi',
	'no_comments_found' => 'No maoni found',
	'no_comments_in_x' => 'No maoni in ^',
	'no_questions_found' => 'No maswali found',
	'no_questions_in_x' => 'No maswali in ^',
	'no_related_qs_title' => 'No related maswali found',
	'no_results_for_x' => 'No results found for ^',
	'no_tags_found' => 'No tags found',
	'no_una_questions_found' => 'No unanswered maswali found',
	'no_una_questions_in_x' => 'No unanswered maswali in ^',
	'no_unselected_qs_found' => 'No maswali found without a selected jibu',
	'no_unupvoteda_qs_found' => 'No maswali found without an upvoted jibu',
	'page_label' => 'Page:',
	'page_next' => 'next',
	'page_not_found' => 'Page not found',
	'page_prev' => 'prev',
	'popular_tags' => 'Most popular tags',
	'questions_tagged_x' => 'Recent maswali tagged ^',
	'recategorized' => 'recategorized',
	'recent_activity_in_x' => 'Recent activity in ^',
	'recent_activity_title' => 'Recent activity',
	'recent_as_in_x' => 'Recently alijibu maswali in ^',
	'recent_as_title' => 'Recently alijibu maswali',
	'recent_cs_in_x' => 'Recently alitoa maoni maswali in ^',
	'recent_cs_title' => 'Recently alitoa maoni maswali',
	'recent_qs_as_in_x' => 'Recent maswali na majibu in ^',
	'recent_qs_as_title' => 'Recent maswali na majibu',
	'recent_qs_in_x' => 'Recent maswali in ^',
	'recent_qs_title' => 'Recent maswali',
	'related_qs_title' => 'Related maswali',
	'remove_favorites' => 'Remove from my favorites',
	'remove_x_favorites' => 'Remove ^ from my favorites',
	'reopened' => 'reopened',
	'reshown' => 'reshown',
	'results_for_x' => 'Search results for ^',
	'retagged' => 'retagged',
	'save_button' => 'Save Changes',
	'search_button' => 'Search',
	'search_explanation' => 'Please enter some text into the search box na try again.',
	'search_title' => 'Search results',
	'selected' => 'selected',
	'send_button' => 'Send',
	'since_x' => 'since ^',
	'suggest_ask' => 'Help get things started by ^1asking a swali^2.',
	'suggest_category_qs' => 'To see more, click for all the ^1questions in hiki kikundi^2.',
	'suggest_qs' => 'To see more, click for the ^1full list of maswali^2.',
	'suggest_qs_tags' => 'To see more, click for the ^1full list of maswali^2 au ^3popular tags^4.',
	'to_x' => 'to ^',
	'unanswered_qs_in_x' => 'Maswali without majibu in ^',
	'unanswered_qs_title' => 'Recent maswali without majibu',
	'unselected_qs_in_x' => 'Maswali without a selected jibu in ^',
	'unselected_qs_title' => 'Recent maswali without a selected jibu',
	'unupvoteda_qs_in_x' => 'Maswali without an upvoted jibu in ^',
	'unupvoteda_qs_title' => 'Recent maswali without an upvoted jibu',
	'upload_limit' => 'Too many uploads - please try again in an hour',
	'view_q_must_be_approved' => 'Your account must be approved to view swali pages. Please wait au ^1add more information^2.',
	'view_q_must_confirm' => 'Please ^5confirm your email address^6 to view swali pages.',
	'view_q_must_login' => 'Please ^1log in^2 au ^3register^4 to view swali pages.',
	'viewed_qs_in_x' => 'Most viewed maswali in ^',
	'viewed_qs_title' => 'Most viewed maswali',
	'vote_disabled_approve' => 'Your account must be approved before you can vote',
	'vote_disabled_down' => 'Voting down is only available to some watumiaji',
	'vote_disabled_down_approve' => 'Your account must be approved before you can vote down',
	'vote_disabled_hidden_post' => 'You cannot vote on hidden chapisho',
	'vote_disabled_hidden_a' => 'You cannot vote on hidden majibu',  // @deprecated
	'vote_disabled_hidden_q' => 'You cannot vote on hidden maswali',  // @deprecated
	'vote_disabled_level' => 'Voting is only available to some watumiaji',
	'vote_disabled_my_post' => 'You cannot vote on your own chapisho',
	'vote_disabled_my_a' => 'You cannot vote on your own majibu',  // @deprecated
	'vote_disabled_my_q' => 'You cannot vote on your own maswali',  // @deprecated
	'vote_disabled_q_page_only' => 'Please view hiki swali to vote',
	'vote_disabled_queued' => 'You can only vote on approved chapisho',
	'vote_down_must_confirm' => 'Please ^5confirm your email address^6 to vote down.',
	'vote_down_popup' => 'Click to vote down',
	'vote_limit' => 'Too many votes received - please try again in an hour',
	'vote_must_confirm' => 'Please ^5confirm your email address^6 to vote.',
	'vote_must_login' => 'Please ^1log in^2 au ^3register^4 to vote.',
	'vote_not_allowed' => 'Voting on hiki is not allowed',
	'vote_up_popup' => 'Click to vote up',
	'voted_down_popup' => 'You have voted hiki down - click to remove vote',
	'voted_qs_in_x' => 'Highest voted maswali in ^',
	'voted_qs_title' => 'Highest voted maswali',
	'voted_up_popup' => 'You have voted hiki up - click to remove vote',
	'written' => '', // blank in English - placeholder for other languages
	'x_ago' => '^ ago',
	'x_answers' => '^ majibu',
	'x_comments' => '^ maoni',
	'x_days' => '^ days',
	'x_disliked' => '^ dislike',
	'x_flags' => '^ flags',
	'x_hours' => '^ hours',
	'x_liked' => '^ like',
	'x_minutes' => '^ minutes',
	'x_months' => '^ months',
	'x_points' => '^ points',
	'x_questions' => '^ maswali',
	'x_seconds' => '^ seconds',
	'x_tags' => '^ tags',
	'x_users' => '^ watumiaji',
	'x_views' => '^ views',
	'x_votes' => '^ votes',
	'x_weeks' => '^ weeks',
	'x_years' => '^ years',
);
